// Package sqlitemigrate is the public runtime API for sqlite-migrate: the
// pieces an embedding binary needs to load, apply, and verify migrations
// generated by the sqlite-migrate CLI. It never imports anything under
// internal/, which is generation-time tooling only the CLI itself needs.
package sqlitemigrate

// Migration represents a single generated migration file: its sequence
// number, name, SQL body, and recorded checksum. Load and LoadDir parse
// migration files (including go:embed filesystems) into Migration values
// for Runner.Apply to consume.
